version: '2'

services:
  builder:
    build: .
    privileged: true
    volumes:
      - ./cache:/var/cache/pacman:delegated
      - ./builds:/tmp/out:delegated
      - ./work:/var/livecd/work:delegated
