#!/bin/bash
set -eu

export LB_BOOTSTRAP_INCLUDE="gnupg"

lb config noauto \
  --apt-indices false \
	--apt-source-archives false \
	--architecture amd64 \
  --archive-areas "main contrib non-free" \
	--binary-images iso-hybrid \
	--cache true \
	--cache-indices true \
	--cache-packages true \
	--clean \
	--distribution buster \
	--memtest none \
	--system live \
	--win32-loader false \
	"${@}"
